### ISSUE TITLE
"Invalid argument(s): Provided content does not align with expectations"

### ISSUE THREAD

**Issue by dkrutskikh** [axel-op/dart_package_analyzer#15]
Last five days dart-package-analyzer crashes on every run.

https://github.com/dart-code-checker/dart-code-metrics/runs/2168640802

2021-03-22T17:54:25.2056965Z ##[group]Running pana
2021-03-22T17:54:25.5128260Z {"logName":"pana","level":"INFO","message":"Running `/flutter/bin/cache/dart-sdk/bin/dart --version`..."}
2021-03-22T17:54:25.5715632Z {"logName":"pana","level":"INFO","message":"Running `flutter --no-version-check --version --machine`..."}
2021-03-22T17:54:26.3455792Z {"logName":"pana","level":"INFO","message":"Running `/flutter/bin/cache/dart-sdk/bin/pub upgrade --verbosity io --no-precompile`..."}
2021-03-22T17:54:29.9193345Z {"logName":"pana","level":"INFO","message":"Analyzing package..."}
2021-03-22T17:54:29.9696760Z {"logName":"pana","level":"INFO","message":"Running `/flutter/bin/cache/dart-sdk/bin/dartanalyzer --options /github/workspace/pana_analysis_options_1616435669958881.g.yaml --format machine bin lib`..."}
2021-03-22T17:54:42.7434141Z {"level":"SHOUT","message":"Problem analyzing /github/workspace","error":"Invalid argument(s): Provided content does not align with expectations.\n`No dart files found at: /github/workspace/lib`","stackTrace":"#0      parseCodeProblem (package:pana/src/code_problem.dart:52:5)\n#1      PackageContext.staticAnalysis.<anonymous closure> (package:pana/src/package_context.dart:121:23)\n#2      MappedIterator.moveNext (dart:_internal/iterable.dart:390:20)\n#3      WhereIterator.moveNext (dart:_internal/iterable.dart:436:22)\n#4      SetMixin.addAll (dart:collection/set.dart:57:23)\n#5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:111:27)\n#6      Iterable.toSet (dart:core/iterable.dart:376:21)\n#7      PackageContext.staticAnalysis (package:pana/src/package_context.dart:123:12)\n<asynchronous suspension>\n#8      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:147:27)\n<asynchronous suspension>\n#9      main (file:///root/.pub-cache/hosted/pub.dartlang.org/pana-0.15.4/bin/pana.dart:163:19)\n<asynchronous suspension>\n"}
2021-03-22T17:54:42.8798897Z ##[endgroup]
2021-03-22T17:54:42.8803460Z ##[error]Pana exited with code 1

**Comment by shamblett** [comment]
I'm seeing this also, was OK for me yesterday though.

**Comment by axel-op** [comment]
After doing some research, I think that this is due to a bug of the `dartanalyzer` command in the latest versions of the Dart SDK (this issue only occurs with the `beta`/`dev` versions of the SDK) . I opened an issue in dart-lang/sdk: https://github.com/dart-lang/sdk/issues/45488.

**Comment by dkrutskikh** [comment]
@axel-op Thank you for your research. Do you have a plan downgrade to stable version of SDK?

**Comment by axel-op** [comment]
> @axel-op Thank you for your research. Do you have a plan downgrade to stable version of SDK? 

No, because of #11.

However, see #5 to customize the version of Flutter for your repo.

**Comment by dkrutskikh** [comment]
As I understand, it was necessary to switch to the beta version when null-safety was on the beta version. Now pub analyse package on stable SDK version  (like this [Analysed with Pana 0.15.4, Flutter 2.0.3, Dart 2.12.2.](https://pub.dev/packages/flutter_bloc/score))

**Comment by axel-op** [comment]
> As I understand, switch on beta need to be only while null-safety will be on beta. Now pub analyse package on stable SDK version  (like this [Analysed with Pana 0.15.4, Flutter 2.0.3, Dart 2.12.2.](https://pub.dev/packages/flutter_bloc/score))

Oh that's right! I guess I can switch to the stable channel again then. Thank you 😊

**Comment by axel-op** [comment]
@dkrutskikh I've pushed ed94c03dc7d1f8d5388e699966c91dfb120abe7f. Can you run your last failing jobs again, and close this issue if it is solved?

**Comment by dkrutskikh** [comment]
@axel-op Thank you. Your fix works well for me. I close this issue.

**Comment by shamblett** [comment]
Yep thanks
